spring:
  zipkin:
    base-url: http://localhost:9411/
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  health:
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
info:
  author: Victor Leão
  mail: leaovic@gmail.com
server:
  port: ${PORT:9999}
message: Mensagem generica

queue:
  movie-service: queue-movie-service
  serie-service: queue-serie-service
  catalog-serie-service: queue-catalog-serie-service
  catalog-movie-service: queue-catalog-movie-service
  


## Resilience4J configs for CircuitBreaker Pattern
resilience4j:
  circuitbreaker:
    instances:
      movie-service:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failueRateThreshold: 50
        waitDurationInOpenState: 50s
        permittedNumberOfCalssInHalfOpenState: 2
        automaticTransitionFromOpenToHalfIfOpenEnabled: true
